# Currently this config file is not used, because during development it is quicker to configure the parameters in the python file itself

parameters:
  - device: "cuda"
  - num_workers: 8
  - manualSeed: 999
  #
  - dataset: "Test_Set_RGB_DISPARITY"
  - shuffle: True
  - channels: 1
  #
  - num_epochs: 100
  - decay_epochs: 50
  - learning_rate: 0.0002
  - batch_size: 1
  - resize_image_to:
    - h: 68
    - w: 120
